RIDER_SERVICE_BASE_PATH: "http://rider-service.perftest:8080"
OPERATION_SERVICE_BASE_PATH: "http://operations-service.perftest:8080"
RECONCILIATION_SERVICE_BASE_PATH: "http://reconciliation-service.perftest:8080"
SETTLEMENT_SERVICE_BASE_PATH: "http://settlement-service.perftest:8080"
SFTP_HOST: "103.246.25.64"
SFTP_USERNAME: "rbh_in_uat"
SFTP_PRIVATE_KEY_FILE: "inbound_robinhood.key"
SMTP_HOST: "email-smtp.ap-southeast-1.amazonaws.com"
SMPT_PORT: "587"
SMTP_USERNAME: "AKIASWI3QINMLQV5VPP7"
SMTP_FROMEMAIL: "tarun.singh2@publicissapient.com"
SMTP_TOEMAIL: "tarun.singh2@publicissapient.com"
AMAZON_S3_BUCKET_NAME: "rider-internal-content-perftest"
