RIDER_SERVICE_BASE_PATH: "http://rider-service.prod:8080"
OPERATION_SERVICE_BASE_PATH: "http://operations-service.prod:8080"
RECONCILIATION_SERVICE_BASE_PATH: "http://reconciliation-service.prod:8080"
SETTLEMENT_SERVICE_BASE_PATH: "http://settlement-service.prod:8080"
SFTP_HOST: "203.155.156.33"
SFTP_USERNAME: "rbh_in_prod"
SFTP_PRIVATE_KEY_FILE: "inbound_robinhood.key"
SMTP_HOST: "email-smtp.ap-southeast-1.amazonaws.com"
SMPT_PORT: "587"
SMTP_USERNAME: "AKIAVRZWB2B7CTXYQLRP"
SMTP_FROMEMAIL: "no-reply-robinhoodrider@robinhood.in.th"
SMTP_TOEMAIL: "GLRider@scbcorp.onmicrosoft.com"
AMAZON_S3_BUCKET_NAME: "rider-internal-content-prod"
