---
# Source: environment/templates/devops-config/deployment/deployment-vars-{{env}}.yml
# This file was generated at  using generator Version: 

DEPLOYMENT:
    ENV: perftest
    NAMESPACE: perftest
    CONFIG_FILES:
        - "src/main/resources/config/tax-service.default.yaml"
        - "src/main/resources/config/tax-service.perftest.yaml"

APP:
    REPLICA: 6
    HPA:
      ENABLED: 1
      MIN_REPLICA: 3
      MAX_REPLICA: 6
      CPU_UTILIZATION: 65
      MEMORY_UTILIZATION: 80
    CONTAINER:
      MEMORY:
        REQUEST: 1Gi
        LIMIT: 1Gi
      CPU:
        REQUEST: 0.5
        LIMIT: 1
    ENVIRONMENT:
      - KEY: logs.Dir
        VALUE: "/apps/logs/perftest/tax-service/"
